In [2]:
import numpy as np
import math

In [3]:
n1=3541 # 町丁目数
m1=34 # 店舗数
dist1=np.zeros((n1,m1))
print(dist1)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [6]:
print(dist1.shape)

(3541, 34)
